//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFPTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public long UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string OriginType { get; set; }
        public string ContactNumber { get; set; }
        public string Nationality { get; set; }
        public bool Status { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ImagePath { get; set; }
    }
}
